import type { CatalogueEntry } from './types';

export const catalogue: readonly CatalogueEntry[] = Object.freeze([
  {
    agent: 'claude-code',
    label: 'Claude Code',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['claude/'],
    trailerPatterns: ['co-authored-by: claude', 'generated with claude code', 'claude-session:'],
    bodyPatterns: ['generated with [claude code]', 'generated with claude code'],
  },
  {
    agent: 'codex',
    label: 'Codex',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['codex/'],
    trailerPatterns: ['co-authored-by: codex'],
    bodyPatterns: [],
  },
  {
    agent: 'copilot',
    label: 'GitHub Copilot',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['copilot/'],
    trailerPatterns: ['co-authored-by: copilot'],
    bodyPatterns: [],
  },
  {
    agent: 'cursor',
    label: 'Cursor',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['cursor/'],
    trailerPatterns: ['co-authored-by: cursor'],
    bodyPatterns: [],
  },
  {
    agent: 'devin',
    label: 'Devin',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['devin/'],
    trailerPatterns: [],
    bodyPatterns: [],
  },
  {
    agent: 'gemini',
    label: 'Gemini',
    kind: 'coding-agent',
    checkAppIds: [],
    botLogins: [],
    reviewerIds: [],
    branchPrefixes: ['gemini/'],
    trailerPatterns: [],
    bodyPatterns: [],
  },
]);
